/**
 * @fileoverview gRPC-Web generated client stub for notifications
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: notifications/notifications.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as notifications_notifications_pb from '../notifications/notifications_pb'; // proto import: "notifications/notifications.proto"


export class NotificationServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendNotification = new grpcWeb.MethodDescriptor(
    '/notifications.NotificationService/SendNotification',
    grpcWeb.MethodType.UNARY,
    notifications_notifications_pb.NotificationRequest,
    notifications_notifications_pb.NotificationResponse,
    (request: notifications_notifications_pb.NotificationRequest) => {
      return request.serializeBinary();
    },
    notifications_notifications_pb.NotificationResponse.deserializeBinary
  );

  sendNotification(
    request: notifications_notifications_pb.NotificationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifications_notifications_pb.NotificationResponse>;

  sendNotification(
    request: notifications_notifications_pb.NotificationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifications_notifications_pb.NotificationResponse) => void): grpcWeb.ClientReadableStream<notifications_notifications_pb.NotificationResponse>;

  sendNotification(
    request: notifications_notifications_pb.NotificationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifications_notifications_pb.NotificationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/notifications.NotificationService/SendNotification',
        request,
        metadata || {},
        this.methodDescriptorSendNotification,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/notifications.NotificationService/SendNotification',
    request,
    metadata || {},
    this.methodDescriptorSendNotification);
  }

}

