/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: auth/auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as auth_auth_pb from '../auth/auth_pb'; // proto import: "auth/auth.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.LoginRequest,
    auth_auth_pb.LoginResponse,
    (request: auth_auth_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.LoginResponse.deserializeBinary
  );

  login(
    request: auth_auth_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.LoginResponse>;

  login(
    request: auth_auth_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.LoginResponse>;

  login(
    request: auth_auth_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/CreateUser',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.CreateUserRequest,
    auth_auth_pb.CreateUserResponse,
    (request: auth_auth_pb.CreateUserRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.CreateUserResponse.deserializeBinary
  );

  createUser(
    request: auth_auth_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.CreateUserResponse>;

  createUser(
    request: auth_auth_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.CreateUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.CreateUserResponse>;

  createUser(
    request: auth_auth_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.CreateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorUpdateUser = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/UpdateUser',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.UpdateUserRequest,
    auth_auth_pb.UpdateUserResponse,
    (request: auth_auth_pb.UpdateUserRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.UpdateUserResponse.deserializeBinary
  );

  updateUser(
    request: auth_auth_pb.UpdateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.UpdateUserResponse>;

  updateUser(
    request: auth_auth_pb.UpdateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.UpdateUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.UpdateUserResponse>;

  updateUser(
    request: auth_auth_pb.UpdateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.UpdateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/UpdateUser',
        request,
        metadata || {},
        this.methodDescriptorUpdateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/UpdateUser',
    request,
    metadata || {},
    this.methodDescriptorUpdateUser);
  }

  methodDescriptorDeleteUser = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/DeleteUser',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.DeleteUserRequest,
    auth_auth_pb.DeleteUserResponse,
    (request: auth_auth_pb.DeleteUserRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.DeleteUserResponse.deserializeBinary
  );

  deleteUser(
    request: auth_auth_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.DeleteUserResponse>;

  deleteUser(
    request: auth_auth_pb.DeleteUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.DeleteUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.DeleteUserResponse>;

  deleteUser(
    request: auth_auth_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.DeleteUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/DeleteUser',
        request,
        metadata || {},
        this.methodDescriptorDeleteUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/DeleteUser',
    request,
    metadata || {},
    this.methodDescriptorDeleteUser);
  }

  methodDescriptorGetUserByToken = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/GetUserByToken',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.GetUserByTokenRequest,
    auth_auth_pb.GetUserResponse,
    (request: auth_auth_pb.GetUserByTokenRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.GetUserResponse.deserializeBinary
  );

  getUserByToken(
    request: auth_auth_pb.GetUserByTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.GetUserResponse>;

  getUserByToken(
    request: auth_auth_pb.GetUserByTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.GetUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.GetUserResponse>;

  getUserByToken(
    request: auth_auth_pb.GetUserByTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.GetUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/GetUserByToken',
        request,
        metadata || {},
        this.methodDescriptorGetUserByToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/GetUserByToken',
    request,
    metadata || {},
    this.methodDescriptorGetUserByToken);
  }

  methodDescriptorGetUserByEmail = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/GetUserByEmail',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.GetUserByEmailRequest,
    auth_auth_pb.GetUserResponse,
    (request: auth_auth_pb.GetUserByEmailRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.GetUserResponse.deserializeBinary
  );

  getUserByEmail(
    request: auth_auth_pb.GetUserByEmailRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.GetUserResponse>;

  getUserByEmail(
    request: auth_auth_pb.GetUserByEmailRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.GetUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.GetUserResponse>;

  getUserByEmail(
    request: auth_auth_pb.GetUserByEmailRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.GetUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/GetUserByEmail',
        request,
        metadata || {},
        this.methodDescriptorGetUserByEmail,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/GetUserByEmail',
    request,
    metadata || {},
    this.methodDescriptorGetUserByEmail);
  }

  methodDescriptorGetUserByUsername = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/GetUserByUsername',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.GetUserByUsernameRequest,
    auth_auth_pb.GetUserResponse,
    (request: auth_auth_pb.GetUserByUsernameRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.GetUserResponse.deserializeBinary
  );

  getUserByUsername(
    request: auth_auth_pb.GetUserByUsernameRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.GetUserResponse>;

  getUserByUsername(
    request: auth_auth_pb.GetUserByUsernameRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.GetUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.GetUserResponse>;

  getUserByUsername(
    request: auth_auth_pb.GetUserByUsernameRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.GetUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/GetUserByUsername',
        request,
        metadata || {},
        this.methodDescriptorGetUserByUsername,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/GetUserByUsername',
    request,
    metadata || {},
    this.methodDescriptorGetUserByUsername);
  }

  methodDescriptorVerifyUser = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/VerifyUser',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.VerifyUserRequest,
    auth_auth_pb.VerifyUserResponse,
    (request: auth_auth_pb.VerifyUserRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.VerifyUserResponse.deserializeBinary
  );

  verifyUser(
    request: auth_auth_pb.VerifyUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.VerifyUserResponse>;

  verifyUser(
    request: auth_auth_pb.VerifyUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.VerifyUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.VerifyUserResponse>;

  verifyUser(
    request: auth_auth_pb.VerifyUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.VerifyUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/VerifyUser',
        request,
        metadata || {},
        this.methodDescriptorVerifyUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/VerifyUser',
    request,
    metadata || {},
    this.methodDescriptorVerifyUser);
  }

}

export class PrivateServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetUserByToken = new grpcWeb.MethodDescriptor(
    '/auth.PrivateService/GetUserByToken',
    grpcWeb.MethodType.UNARY,
    auth_auth_pb.PrivateGetUserByTokenRequest,
    auth_auth_pb.PrivateGetUserResponse,
    (request: auth_auth_pb.PrivateGetUserByTokenRequest) => {
      return request.serializeBinary();
    },
    auth_auth_pb.PrivateGetUserResponse.deserializeBinary
  );

  getUserByToken(
    request: auth_auth_pb.PrivateGetUserByTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<auth_auth_pb.PrivateGetUserResponse>;

  getUserByToken(
    request: auth_auth_pb.PrivateGetUserByTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: auth_auth_pb.PrivateGetUserResponse) => void): grpcWeb.ClientReadableStream<auth_auth_pb.PrivateGetUserResponse>;

  getUserByToken(
    request: auth_auth_pb.PrivateGetUserByTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: auth_auth_pb.PrivateGetUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.PrivateService/GetUserByToken',
        request,
        metadata || {},
        this.methodDescriptorGetUserByToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.PrivateService/GetUserByToken',
    request,
    metadata || {},
    this.methodDescriptorGetUserByToken);
  }

}

