/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: chat/chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chat_chat_pb from '../chat/chat_pb'; // proto import: "chat/chat.proto"


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/SendMessage',
    grpcWeb.MethodType.UNARY,
    chat_chat_pb.SendMsgRequest,
    chat_chat_pb.ChatResponse,
    (request: chat_chat_pb.SendMsgRequest) => {
      return request.serializeBinary();
    },
    chat_chat_pb.ChatResponse.deserializeBinary
  );

  sendMessage(
    request: chat_chat_pb.SendMsgRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_chat_pb.ChatResponse>;

  sendMessage(
    request: chat_chat_pb.SendMsgRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_chat_pb.ChatResponse) => void): grpcWeb.ClientReadableStream<chat_chat_pb.ChatResponse>;

  sendMessage(
    request: chat_chat_pb.SendMsgRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_chat_pb.ChatResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

}

